build:
  base: .
  publish: ./build/
  command: yarn build
  processing:
    skip_processing: false
    css:
      bundle: true
      minify: true
    js:
      bundle: true
      minify: true
    images:
      compress: true

headers:
  - for: /*
    values:
      X-Frame-Options: DENY
      X-XSS-Protection: 1; mode=block
      Content-Security-Policy: default-src 'self'
